# **Tutorial 1: Membaca File**

oleh: Jihan A. As-sya'bani (jihan.ahmad.a@mail.ugm.ac.id)

**PENTING!**
Sebelum memulai tutorial ini, pastikan file data (dalam format *.csv atau *.parquet) berada dalam satu folder yang sama dengan file ini! Anda bisa mendownload salah satu (atau kedua) format tersebut dan simpan dalam satu folder dengan file ini.

Data angin dari metmast di Ciheras disimpan dalam 2 format berbeda: 
- csv
- parquet

Library utama yang akan digunakan untuk membaca file ini adalah `pandas` [1]. Pandas adalah library yang memungkinkan kita untuk melakukan manipulasi data berupa tabel dengan melakukan manipulasi baris dan kolom yang disebut sebagai `dataframe`. Dataframe memungkinkan kita mengolah data seperti saat kita melakukan olah data menggunakan perangkat lunak *spreadsheet* seperti Microsoft Excel. 

Pandas dapat diimpor menggunakan perintah:

`import pandas`

Terkadang saat library pandas diimpor, ia disingkat sebagai `pd` menggunakan perintah: 

```import pandas as pd```

[1] https://pandas.pydata.org/docs/user_guide/index.html

Jalankan sel di bawah ini untuk mengimpor library pandas:

In [1]:
# Mengimpor library pandas 
import pandas as pd

## **1.1 File CSV**

#### **1.1.1. Sekilas tentang format csv**

Format *csv (comma separated values)* merupakan format untuk menyimpan tabel data yang sebagai teks yang data dari satu kolom dengan kolom lainnya dipisahkan oleh tanda koma `,` [1]. Format data ini biasanya menggunakan baris pertama sebagai nama kolom dan baris-baris berikutnya sebagai isi data untuk setiap kolom:

`kolom a, kolom b, kolom c, ..., kolom n`

`data a1, data b1, data c1, ..., data n1`

`   ... `

`data an, data bn, data cn, ..., data nn`

**Kelebihan & Kekurangan**

Format ini mudah dibaca menggunakan berbagai macam perangkat lunak, baik perangkat lunak *spreadsheet* (seperti Microsoft Excel, Open Office, Libre Office,) maupun perangkat lunak pembaca teks seperti notepad.

Karena data disimpan sebagai teks murni (`string`), ada beberapa kekurangan dari penyimpanan data menggunakan format ini:
- Perubahan data secara tidak disengaja. Hal ini bisa disebabkan oleh beberapa hal:
	- Perubahan data dari `string` menjadi `float` atau `integer` oleh pandas. Saat membaca kolom pada file csv, pandas biasanya akan membuat asumsi jenis data pada kolom tersebut. Misalnya data pada kolom dengan format '123.45' akan dianggap sebagai `float` secara otomatis, sedangkan data pada kolom dengan format '12345' akan dianggap sebagai `integer`.
	- Tidak sengaja mengubah data karena isi data terekspos secara langsung.  
- Ukuran file yang cukup besar

[1] https://en.wikipedia.org/wiki/Comma-separated_values

#### **1.1.2. Membaca file csv menggunakan pandas**

Perintah untuk membaca file csv menggunakan pandas adalah:

`df = pd.read_csv(path_ke_file)`

Jalankan sel berikut untuk membaca file csv:

In [2]:
# Mendefinisikan path file
path = "LBN_2025_11.csv"

# Membaca file dari path sebagai dataframe 'df':
df = pd.read_csv(path)

# Melihat isi 5 baris pertama dari dataframe df: 
print(df.head())

   Unnamed: 0                 time  record_no  wdir_15m  wspd_10m  wspd_15m
0           0  2025-11-01 00:00:00    8830830     6.418      0.00      0.00
1           1  2025-11-01 00:00:01    8830831     5.980      1.25      1.25
2           2  2025-11-01 00:00:02    8830832     6.418      0.00      1.25
3           3  2025-11-01 00:00:03    8830833     7.488      0.00      1.25
4           4  2025-11-01 00:00:04    8830834     9.140      1.25      1.25

Untuk membaca "seluruh" isi tabel, dapat dilakukan dengan perintah `print(df)`, maka pandas akan menuliskan 5 baris pertama dan 5 baris terkahir beserta ukuran tabel (jumlah baris dan jumlah kolom). Jalankan sel berikut untuk melihat seluruh isi tabel:

In [3]:
print(df)

         Unnamed: 0                 time  record_no  wdir_15m  wspd_10m  \
0                 0  2025-11-01 00:00:00    8830830     6.418      0.00
1                 1  2025-11-01 00:00:01    8830831     5.980      1.25
2                 2  2025-11-01 00:00:02    8830832     6.418      0.00
3                 3  2025-11-01 00:00:03    8830833     7.488      0.00
4                 4  2025-11-01 00:00:04    8830834     9.140      1.25
...             ...                  ...        ...       ...       ...
2439239     2439239  2025-11-30 23:59:55   11422825   312.400      1.25
2439240     2439240  2025-11-30 23:59:56   11422826   313.000      1.25
2439241     2439241  2025-11-30 23:59:57   11422827   327.100      0.00
2439242     2439242  2025-11-30 23:59:58   11422828   332.100      1.25
2439243     2439243  2025-11-30 23:59:59   11422829   332.100      0.00

         wspd_15m
0            0.00
1            1.25
2            1.25
3            1.25
4            1.25
...           ...
2439239      1.25
2439240      1.25
2439241      0.00
2439242      1.25
2439243      0.00

[2439244 rows x 6 columns]

atau bisa juga cukup dengan memanggil dataframe tersebut secara langsung:

In [4]:
df

,Unnamed: 0,time,record_no,wdir_15m,wspd_10m,wspd_15m
0,0,2025-11-01 00:00:00,8830830,6.418,0.00,0.00
1,1,2025-11-01 00:00:01,8830831,5.980,1.25,1.25
2,2,2025-11-01 00:00:02,8830832,6.418,0.00,1.25
3,3,2025-11-01 00:00:03,8830833,7.488,0.00,1.25
4,4,2025-11-01 00:00:04,8830834,9.140,1.25,1.25
...,...,...,...,...,...,...
2439239,2439239,2025-11-30 23:59:55,11422825,312.400,1.25,1.25
2439240,2439240,2025-11-30 23:59:56,11422826,313.000,1.25,1.25
2439241,2439241,2025-11-30 23:59:57,11422827,327.100,0.00,0.00
2439242,2439242,2025-11-30 23:59:58,11422828,332.100,1.25,1.25
2439243,2439243,2025-11-30 23:59:59,11422829,332.100,0.00,0.00

Pada file di atas terdapat kolom bernama `Unnamed: 0`, kolom ini merupakan indeks untuk setiap baris yang ikut terekspor pada saat file csv ini dibuat. Kolom ini dapat dihapus menggunakan perintah berikut:

`df.drop(columns=['daftar_nama_kolom_untuk_dibuang'])`

In [5]:
# Menghapus kolom 'Unnamed: 0':
df = df.drop(columns=['Unnamed: 0'])

# Melihat isi dataframe setelah kolom dihapus:
df

                        time  record_no  wdir_15m  wspd_10m  wspd_15m
0        2025-11-01 00:00:00    8830830     6.418      0.00      0.00
1        2025-11-01 00:00:01    8830831     5.980      1.25      1.25
2        2025-11-01 00:00:02    8830832     6.418      0.00      1.25
3        2025-11-01 00:00:03    8830833     7.488      0.00      1.25
4        2025-11-01 00:00:04    8830834     9.140      1.25      1.25
...                      ...        ...       ...       ...       ...
2439239  2025-11-30 23:59:55   11422825   312.400      1.25      1.25
2439240  2025-11-30 23:59:56   11422826   313.000      1.25      1.25
2439241  2025-11-30 23:59:57   11422827   327.100      0.00      0.00
2439242  2025-11-30 23:59:58   11422828   332.100      1.25      1.25
2439243  2025-11-30 23:59:59   11422829   332.100      0.00      0.00

[2439244 rows x 5 columns]

## **1.2. File Parquet**

#### **1.2.1 Sekilas tentang format Parquet**

Parquet merupakan format untuk menyimpan data tabulasi dalam sebagai data biner yang dikembangkan oleh Apache[1]. Setiap kolom pada parquet sudah disimpan sebagai tipe datanya masing-masing (`string`, `float`, `integer`, dll) secara terpisah dan dikompresi secara terpisah. 

**Kelebihan & Kekurangan**

Kelebihan menyimpan data dalam format parquet adalah ukuran file yang relatif kecil. Namun format ini biasanya tidak langsung dapat dibaca oleh perangkat lunak spreadsheet. Hal ini juga secara tidak langsung memberikan proteksi terhadap isi data dari modifikasi secara tidak sengaja. 

[1] https://en.wikipedia.org/wiki/Apache_Parquet

#### **1.2.2 Membaca file parquet menggunakan pandas**

Perintah untuk membaca file csv menggunakan pandas adalah:

`df = pd.read_parquet(path_ke_file)`

Jalankan sel berikut untuk membaca file parquet:

In [6]:
# Mendefinisikan path file
path = "LBN_2025_11.parquet"

# Membaca file dari path sebagai dataframe 'df':
df = pd.read_parquet(path)

# Melihat isi 5 baris pertama dari dataframe df: 
df

                       time  record_no  wdir_15m  wspd_10m  wspd_15m
0       2025-11-01 00:00:00    8830830     6.418      0.00      0.00
1       2025-11-01 00:00:01    8830831     5.980      1.25      1.25
2       2025-11-01 00:00:02    8830832     6.418      0.00      1.25
3       2025-11-01 00:00:03    8830833     7.488      0.00      1.25
4       2025-11-01 00:00:04    8830834     9.140      1.25      1.25
...                     ...        ...       ...       ...       ...
2439239 2025-11-30 23:59:55   11422825   312.400      1.25      1.25
2439240 2025-11-30 23:59:56   11422826   313.000      1.25      1.25
2439241 2025-11-30 23:59:57   11422827   327.100      0.00      0.00
2439242 2025-11-30 23:59:58   11422828   332.100      1.25      1.25
2439243 2025-11-30 23:59:59   11422829   332.100      0.00      0.00

[2439244 rows x 5 columns]

## **1.3. Membaca beberapa file secara bersamaan**

**PENTING!** Sebelum memulai bagian ini, siapkan sebuah folder berisi beberapa file csv atau parquet.

Untuk membaca beberapa file secara bersamaan, kita memerlukan bantuan library lainnya bernama `os`. Library ini berfungsi untuk membantu kita mengidentifikasi file-file yang ada di dalam suatu direktori. 

Untuk mengimpor library ini, jalankan sel berikut:

In [7]:
import os

Dalam contoh ini, kita menyimpan beberapa data dari metmast di dalam folder `data` yang berada dalam satu folder yang sama dengan file ini. jalankan sel berikut untuk membaca file-file yang ada dalam folder data:

In [8]:
# Mendefinisikan path:
path = "data"

# Mendapatkan daftar file di dalam path:
files = os.listdir(path)

# Lihat isi file di dalam direktori:
print(files)

['LBN_2025_10.parquet', 'LBN_2025_11.csv', 'LBN_2025_11.parquet', 'LBN_2025_12.parquet', 'LBN_2026_01.parquet', 'LBN_2026_02.csv', 'LBN_2026_02.parquet', 'LBN_2026_03.parquet', 'LBN_2026_04.parquet']

Kita lihat bahwa ada beberapa file dalam format yang berbeda. Untuk bisa membaca beberapa file, kita perlu memilah hanya untuk file dengan format yang sama (hanya parquet atau hanya csv). Untuk melakukannya kita perlu menambahkan kondisi `endswith('format_yang_diinginkan')`

In [9]:
# Mengambil daftar file parquet di dalam direktori:
files = [f for f in os.listdir(path) if f.endswith(".parquet")]

# Melihat daftar file yang sudah diseleksi:
print(files)

['LBN_2025_10.parquet', 'LBN_2025_11.parquet', 'LBN_2025_12.parquet', 'LBN_2026_01.parquet', 'LBN_2026_02.parquet', 'LBN_2026_03.parquet', 'LBN_2026_04.parquet']

Selanjutnya gunakan loop `for` untuk membaca setiap file satu persatu dan menggabungkan file-file tersebut. Setiap file dapat dibaca menggunakan perintah `pd.read_csv()` atau `pd.read_parquet()` seperti pada bagian sebelumnya. Lalu digabungkan (`concatenate`) sebagai satu dataframe dimana pandas akan secara otomatis menggabungkan data dengan nama kolom yang sama. 

Syarat untuk bisa menggabungkan beberapa dataframe adalah dataframe-dataframe tersebut memiliki jumlah kolom yang sama. 

Jalankan sel berikut untuk menggabungkan file-file tersebut:

In [10]:
# Siapkan list kosong untuk menyimpan sementara setiap dataframe dari setiap file parquet
dataframes = []

# Membaca setiap file di dalam variabel files:
for f in files:

	# Membaca file f sebagai dataframe df:
	df = pd.read_parquet(f)

	# Menambahkan dataframe 'df' ke dalam list 'dataframes':
	dataframes.append(df)

# Menggabungkan seluruh dataframe di dalam list dataframes sebagai satu dataframe:
dataframes = pd.concat(dataframes)

# Melihat isi dataframe
dataframes

                       time  record_no  wdir_15m  wspd_10m  wspd_15m
0       2025-10-14 22:33:13    7356823     37.15      2.50      1.25
1       2025-10-14 22:33:14    7356824     27.81      1.25      1.25
2       2025-10-14 22:33:15    7356825     24.51      1.25      2.50
3       2025-10-14 22:33:16    7356826     24.07      1.25      1.25
4       2025-10-14 22:33:17    7356827     24.51      1.25      1.25
...                     ...        ...       ...       ...       ...
1769795 2026-04-30 23:59:55    6482878    333.60      0.00      1.25
1769796 2026-04-30 23:59:56    6482879    328.80      0.00      1.25
1769797 2026-04-30 23:59:57    6482880    329.70      0.00      0.00
1769798 2026-04-30 23:59:58    6482881    329.90      0.00      1.25
1769799 2026-04-30 23:59:59    6482882    329.50      0.00      1.25

[10782486 rows x 5 columns]

## **1.4 Ringkasan Akhir**

#### **1.4.1 Membaca satu file**

In [11]:
# Mengimpor library:
import pandas as pd 

# Mendefinisikan path file
path = "LBN_2025_11.csv"

# Membaca file dari path sebagai dataframe 'df':
df = pd.read_csv(path)

# Melihat isi 5 baris pertama dari dataframe df: 
df

,Unnamed: 0,time,record_no,wdir_15m,wspd_10m,wspd_15m
0,0,2025-11-01 00:00:00,8830830,6.418,0.00,0.00
1,1,2025-11-01 00:00:01,8830831,5.980,1.25,1.25
2,2,2025-11-01 00:00:02,8830832,6.418,0.00,1.25
3,3,2025-11-01 00:00:03,8830833,7.488,0.00,1.25
4,4,2025-11-01 00:00:04,8830834,9.140,1.25,1.25
...,...,...,...,...,...,...
2439239,2439239,2025-11-30 23:59:55,11422825,312.400,1.25,1.25
2439240,2439240,2025-11-30 23:59:56,11422826,313.000,1.25,1.25
2439241,2439241,2025-11-30 23:59:57,11422827,327.100,0.00,0.00
2439242,2439242,2025-11-30 23:59:58,11422828,332.100,1.25,1.25
2439243,2439243,2025-11-30 23:59:59,11422829,332.100,0.00,0.00

#### **1.4.2 Membaca banyak file**

In [12]:
# Mengimpor library
import pandas as pd 
import os 

# Mendefinisikan path berisi file-file data metmast:
path = "data"

# Mengambil daftar file parquet di dalam direktori:
files = [f for f in os.listdir(path) if f.endswith(".parquet")]

# Siapkan list kosong untuk menyimpan sementara setiap dataframe dari setiap file parquet
dataframes = []

# Membaca setiap file di dalam variabel files:
for f in files:

	# Membaca file f sebagai dataframe df:
	df = pd.read_parquet(f)

	# Menambahkan dataframe 'df' ke dalam list 'dataframes':
	dataframes.append(df)

# Menggabungkan seluruh dataframe di dalam list dataframes sebagai satu dataframe:
dataframes = pd.concat(dataframes)

# Melihat isi dataframe
dataframes

                       time  record_no  wdir_15m  wspd_10m  wspd_15m
0       2025-10-14 22:33:13    7356823     37.15      2.50      1.25
1       2025-10-14 22:33:14    7356824     27.81      1.25      1.25
2       2025-10-14 22:33:15    7356825     24.51      1.25      2.50
3       2025-10-14 22:33:16    7356826     24.07      1.25      1.25
4       2025-10-14 22:33:17    7356827     24.51      1.25      1.25
...                     ...        ...       ...       ...       ...
1769795 2026-04-30 23:59:55    6482878    333.60      0.00      1.25
1769796 2026-04-30 23:59:56    6482879    328.80      0.00      1.25
1769797 2026-04-30 23:59:57    6482880    329.70      0.00      0.00
1769798 2026-04-30 23:59:58    6482881    329.90      0.00      1.25
1769799 2026-04-30 23:59:59    6482882    329.50      0.00      1.25

[10782486 rows x 5 columns]